default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: asd_delopment


test:
  <<: *default
  database: asd_est

production:
  <<: *default
  database: test_blog_production
  username: asd
  password: <%= ENV['ASD_DATABASE_PASSWORD'] %>