default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: somartestingapp_delopment


test:
  <<: *default
  database: somartestingapp_test

production:
  <<: *default
  database: somartestingapp_production
  username: somartestingapp
  password: <%= ENV['ASD_DATABASE_PASSWORD'] %>