default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: somar
  password: jamalm1990

development:
  <<: *default
  database: news_blog_develent
test:
  <<: *default
  database: news_blog_te

production:
  database: news_blog_pro
  <<: *default
  # password: <%= ENV['NEWS_BLOG_DATABASE_PASSWORD'] %>
