default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: somar
  password: jamalm1990

development:
  <<: *default
  database: news_blog_development
test:
  <<: *default
  database: news_blog_test

production:
  database: news_blog_production
  <<: *default
  # password: <%= ENV['NEWS_BLOG_DATABASE_PASSWORD'] %>
